# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
change-id = 133207

[llvm]
targets = "AArch64;RISCV;X86"
download-ci-llvm = false

[target.x86_64-unknown-linux-gnu]
llvm-config="../llvm/build/bin/llvm-config"
llvm-filecheck="../llvm/build/bin/FileCheck"

[target.aarch64-apple-darwin]
llvm-config="../llvm/build/bin/llvm-config"
llvm-filecheck="..//llvm/build/bin/FileCheck"

[build]
target = [
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "riscv32i-unknown-none-elf",
    "riscv64gc-unknown-none-elf",
    "riscv64imac-unknown-none-elf"
]
